version: 0.2

phases:
    install:
        runtime-versions:
            docker: 18
    pre_build:
        commands:
        - echo Installing source NPM dependencies...

artifacts:
    type: zip
    files:
        - package.json