version: '3.7'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    volumes:
      - ./src:/home/node/app/src
      - ./nodemon.json:/home/node/app/nodemon.json
    container_name: api
    expose:
      - '4001'
    ports:
      - '4001:4001'
    command: npm run dev
