version: '3.7'

services:
  db:
    image: mongo
    restart: always
    deploy:
      replicas: 1
    ports:
      - 27017:27017
  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    container_name: api
    expose:
      - '4001'
    ports:
      - '4001:4001'
    depends_on:
      - db
    command: npm run dev